services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: scorekeeper
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bullseye
    volumes:
      # Mount the init.sql file into the initialization directory
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: scorekeeper
      DB_PASSWORD: secret
      DB_NAME: bullseye
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: